/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bizbuilder;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;




import javax.swing.JOptionPane;
/**
 *
 * @author THANATOS
 */
public class salary_form extends javax.swing.JFrame {
    
    /**
     * Creates new form salary_from
     */
    public salary_form() {
        initComponents();
       
        
        // Call a method to populate the combo box
       populateComboBox();
       
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        epf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        monthly_salary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        payable_salary = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        emid = new rojerusan.RSComboMetro();
        salary_credit_date = new com.toedter.calendar.JDateChooser();
        salary_month = new rojerusan.RSComboMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Employee ID");

        epf.setEditable(false);
        epf.setForeground(new java.awt.Color(102, 102, 255));
        epf.setText("RS.");
        epf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        epf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                epfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                epfFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Salary Month");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Salary Credit Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Monthly Salary");

        monthly_salary.setForeground(new java.awt.Color(102, 102, 255));
        monthly_salary.setText("RS.");
        monthly_salary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        monthly_salary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthly_salaryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthly_salaryFocusLost(evt);
            }
        });
        monthly_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthly_salaryActionPerformed(evt);
            }
        });
        monthly_salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monthly_salaryKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("EPF");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Payable Salary");

        payable_salary.setEditable(false);
        payable_salary.setForeground(new java.awt.Color(102, 102, 255));
        payable_salary.setText("RS.");
        payable_salary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        payable_salary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                payable_salaryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                payable_salaryFocusLost(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Save");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        emid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ..." }));
        emid.setColorArrow(new java.awt.Color(102, 102, 255));
        emid.setColorBorde(new java.awt.Color(102, 102, 255));
        emid.setColorFondo(new java.awt.Color(102, 102, 255));
        emid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emidActionPerformed(evt);
            }
        });

        salary_credit_date.setBackground(new java.awt.Color(255, 255, 255));
        salary_credit_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        salary_credit_date.setForeground(new java.awt.Color(102, 102, 255));
        salary_credit_date.setDateFormatString("dd-MM-yyyy");
        salary_credit_date.setDoubleBuffered(false);

        salary_month.setBorder(null);
        salary_month.setMaximumRowCount(5);
        salary_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ...", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(payable_salary)
                                .addComponent(monthly_salary)
                                .addComponent(epf)
                                .addComponent(emid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salary_credit_date, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(salary_month, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salary_month, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salary_credit_date, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monthly_salary)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payable_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payable_salaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payable_salaryFocusGained
        // TODO add your handling code here:
        if(payable_salary.getText().equals("RS.")){
        payable_salary.setText("");
        payable_salary.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_payable_salaryFocusGained

    private void payable_salaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payable_salaryFocusLost
        // TODO add your handling code here:
        if(payable_salary.getText().equals("")){
        payable_salary.setText("RS.");
        payable_salary.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_payable_salaryFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clearfields();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            if(validateInput()== true){
            insertCustomerDetailstoDb();
            clearfields();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void emidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emidActionPerformed

    private void monthly_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthly_salaryActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_monthly_salaryActionPerformed

    private void monthly_salaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthly_salaryFocusGained
        // TODO add your handling code here:
        if(monthly_salary.getText().equals("RS.")){
        monthly_salary.setText("");
        monthly_salary.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_monthly_salaryFocusGained

    private void monthly_salaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthly_salaryFocusLost
        // TODO add your handling code here:
        if(monthly_salary.getText().equals("")){
        monthly_salary.setText("RS.");
        monthly_salary.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_monthly_salaryFocusLost

    private void epfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epfFocusGained
        // TODO add your handling code here:
        if(epf.getText().equals("RS.")){
        epf.setText("");
        epf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_epfFocusGained

    private void epfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epfFocusLost
        // TODO add your handling code here:
        if(epf.getText().equals("")){
        epf.setText("RS.");
        epf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_epfFocusLost

    private void monthly_salaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthly_salaryKeyReleased
        // TODO add your handling code here:
        double ms = Double.parseDouble(monthly_salary.getText());
        double cEPF = (ms*10)/100;
        epf.setText(Double.toString(cEPF));
        
        double cps = (ms-cEPF);
        payable_salary.setText(Double.toString(cps));
    }//GEN-LAST:event_monthly_salaryKeyReleased
    
    private void populateComboBox() {
       String sql = "SELECT * FROM employee";
    try {
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            emid.addItem(rs.getString("employee_id"));
        }                
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inserting records: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
     public void insertCustomerDetailstoDb()
    {
        int eid = Integer.parseInt(emid.getSelectedItem().toString());
        double ms = Double.parseDouble(monthly_salary.getText());
        double EPF = Double.parseDouble(epf.getText());
        double ps = Double.parseDouble(payable_salary.getText());
        String date = (salary_credit_date.getDate().toString());
        String sdate = salary_month.getSelectedItem().toString();
        
        try{
        Connection con = DBConnection.getConnection();
        String sql = "insert into salary (employee_id,salary_month,credited_date,salary,epf,payable_salary) values(?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1,eid);
        pst.setString(2,sdate);
        pst.setString(3, date);
        pst.setDouble(4,ms);
        pst.setDouble(5,EPF);
        pst.setDouble(6,ps);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"insertion sucessful");
        
        }catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error inserting records: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     
     public void clearfields(){
         monthly_salary.setText("RS.");
         epf.setText("RS.");
         payable_salary.setText("RS.");
         emid.setSelectedIndex(0);
         salary_month.setSelectedIndex(0);
         salary_credit_date.setDate(null); 
     } 
    
    public boolean validateInput() {
        
    if (emid.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select Employee ID.");
        return false; // Validation failed
    }

    if (salary_month.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select Salary Month.");
        return false; // Validation failed
    }
    
    Date scd = salary_credit_date.getDate();
    if (scd == null) {
        JOptionPane.showMessageDialog(this, "Please select a date from the calendar.");
        return false; // Validation failed
    }
    
    String ms_text = monthly_salary.getText();
    if (ms_text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a value for Monthly Salary.");
        return false; // Validation failed
    }
 
    

    // All validation checks passed
    return true;
}

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSComboMetro emid;
    private javax.swing.JTextField epf;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monthly_salary;
    private javax.swing.JTextField payable_salary;
    private com.toedter.calendar.JDateChooser salary_credit_date;
    private rojerusan.RSComboMetro salary_month;
    // End of variables declaration//GEN-END:variables
}
