/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bizbuilder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author THANATOS
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_signin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_un = new javax.swing.JTextField();
        con_pw_show = new javax.swing.JCheckBox();
        pw_show = new javax.swing.JCheckBox();
        txt_cpw = new javax.swing.JPasswordField();
        txt_pw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome back! ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your credentials to log in.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign in to access your account.");

        btn_signin.setBackground(new java.awt.Color(255, 255, 255));
        btn_signin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_signin.setForeground(new java.awt.Color(102, 102, 255));
        btn_signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/log-out.png"))); // NOI18N
        btn_signin.setText("SIGNIN");
        btn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(btn_signin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(btn_signin)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Get started with a new account.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("User Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Confrim Your Password");

        btn_create.setBackground(new java.awt.Color(102, 102, 255));
        btn_create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user-account.png"))); // NOI18N
        btn_create.setText("Create Account");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));

        txt_un.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));

        con_pw_show.setBackground(new java.awt.Color(255, 255, 255));
        con_pw_show.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        con_pw_show.setForeground(new java.awt.Color(102, 102, 255));
        con_pw_show.setText("Show");
        con_pw_show.setToolTipText("");
        con_pw_show.setBorder(null);
        con_pw_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_pw_showActionPerformed(evt);
            }
        });

        pw_show.setBackground(new java.awt.Color(255, 255, 255));
        pw_show.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pw_show.setForeground(new java.awt.Color(102, 102, 255));
        pw_show.setText("Show");
        pw_show.setToolTipText("");
        pw_show.setBorder(null);
        pw_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_showActionPerformed(evt);
            }
        });

        txt_cpw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));

        txt_pw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_create)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pw_show))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(con_pw_show))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pw, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_un, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_cpw, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_un, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pw_show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(txt_cpw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(con_pw_show)
                .addGap(6, 6, 6)
                .addComponent(btn_create)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // TODO add your handling code here:
         if( validateSignup()== true)
        {
            if(checkDuplicateUsers()== true)
            {
                JOptionPane.showMessageDialog(this, "Username Already Exists");
            }
            else if(passwordMatch() == true)
            {
                JOptionPane.showMessageDialog(this, "Password doen't matched");
            }
            else
            {
                inserSignupDetails();                
            }
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signinActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        signin s = new signin();
        s.setVisible(true);
    }//GEN-LAST:event_btn_signinActionPerformed

    private void pw_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_showActionPerformed
        // TODO add your handling code here:
        if (pw_show.isSelected()) 
        {
            txt_pw.setEchoChar((char) 0); // Show characters            
        }
        else 
        {
            txt_pw.setEchoChar('\u25cf'); // Hide characters            
        }
    }//GEN-LAST:event_pw_showActionPerformed

    private void con_pw_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_pw_showActionPerformed
        // TODO add your handling code here:
        if (con_pw_show.isSelected()) 
        {
            txt_cpw.setEchoChar((char) 0); // Show characters
        } else 
        {
            txt_cpw.setEchoChar('\u25cf'); // Hide characters
        }
    }//GEN-LAST:event_con_pw_showActionPerformed
    //insert user details
    public void inserSignupDetails()
    {
        String fn = txt_un.getText();        
        String email = txt_email.getText();
        String pw = txt_pw.getText();
        
        try
        {
            //Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/biz","root","");
            Connection con = DBConnection.getConnection();
            /*
            if(con !=null)
            {
                JOptionPane.showMessageDialog(this, "TRUE");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Fail");
            }
            */
            
            String sql = "insert into user (user_name,email,password) values(?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1,fn);
            pst.setString(2,email);
            pst.setString(3,pw);            
                    
            int updateRowCount = pst.executeUpdate();
            
            if(updateRowCount>0)
            {
                JOptionPane.showMessageDialog(this, "User Account Created");
                signin s = new signin();
                s.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Failed to Create Account");
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
            
    }
    
//Validation    
    public boolean validateSignup()
    {
        String fn = txt_un.getText();        
        String email = txt_email.getText();
        String pw = txt_pw.getText();
        
        if(fn.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter User Name");
            return false;
        }
        if(email.equals("") || !email.matches("^.+@.+\\..+$"))
        {
            JOptionPane.showMessageDialog(this, "Enter Valid Email");
            return false;
        }
        if(pw.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Password");
            return false;
        }
        
        return true;
    }
    
//Check Duplicate Users
    public boolean checkDuplicateUsers()
    {
        String fn = txt_un.getText();
        boolean isExist = true;
        
        try
        {
            Connection con = DBConnection.getConnection();
            /*
            if(con !=null)
            {
                JOptionPane.showMessageDialog(this, "TRUE");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Fail");
            }
            */
            String sql = "select * from user where user_name =?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1,fn);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                isExist = true;
            }
            else
            {
                isExist = false;
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
            
        
        return isExist;
    }
    
//Confirm Password Matching
    public boolean passwordMatch()
    {
        boolean matched = true;
        
        String pw = txt_pw.getText();
        String cpw = txt_cpw.getText();
        
        if(!pw.equals(cpw))
        {
            matched = true;            
        }
        else
        {
            matched = false;
        }
        
        return matched;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_signin;
    private javax.swing.JCheckBox con_pw_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox pw_show;
    private javax.swing.JPasswordField txt_cpw;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_pw;
    private javax.swing.JTextField txt_un;
    // End of variables declaration//GEN-END:variables
}
